### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Add unit test with `unittest` module.
- Let every test functions be the one `test_profanity_check` class.
- Using the `unittest` module assertion to assert the `list` and `value`.

### CODE REVIEW

**Comment by vzhou842** [comment]
hey, thanks for the PR! As far as I can tell all this does is switch from `pytest` to `unittest`, which I don't think there's a good enough reason for right now. `pytest` is commonly used and has less boilerplate than `unittest`, which works well with the very simple tests I have for this project. Would love to hear rationale for switching if you feel strongly about it, though!

**Comment by peter279k** [comment]
@vzhou842, thank you for your reply. Using `unittest` module to enhance the tests because the `unittest` module can provide the completed assertion approaches.

If we want to assert the values are equal, we can use the `assertEqual` to complete this.

We can use the `assertListEqual` to assert the expected list is equal to actual list result.

Using the right assertion I think it's important because we need to know what kinds of expected value is equal to actual value from assertions.

**Comment by vzhou842** [comment]
@peter279k As far as I know the existing `pytest` implementation already does the same thing that using `assertListEqual` etc would do? This PR doesn't actually change the semantics of the tests, it only changes the implementation to use `unittest` instead of `pytest`. If you try to play around with the existing implementation you should see that it works as you'd expect.

**Comment by peter279k** [comment]
According to the `pytest` [documentation](https://docs.pytest.org/en/latest/assert.html), the `pytest` only has the `assert` statament to check the expected is same as result value.

I think we use the `unittest` module because it can provide many different knids of assertions to help us to understand what types are expected and result value is same.

I know you just want to keep `pytest` testing, but I just notice that the `pytest` is not good enough to do the unit test.

**Pull request closed without merging**
