### PR TITLE
Retrained model with scikit-learn 0.23.2

### PR DESCRIPTION
**Pull request by owenjones**
Update on koti's PR to retrain the model with scikit-learn 0.23.2 to hide warnings (Trying to unpickle <...> from version 0.23.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.)

### CODE REVIEW

**Comment by menkotoglou** [comment]
Many thanks for your contribution @owenjones. Is it possible for you to submit a pull request on [Dimitry's fork](https://github.com/dimitrismistriotis/profanity-check) as well? We consider releasing it as a Python package.

**Comment by owenjones** [comment]
Sure - have just submitted a pull request there

**Comment by menkotoglou** [comment]
Thank you very much.

**Comment by mjam03** [comment]
Hey, just another voice saying that would be great if this PR was merged into master (and version released for pip). I think this repo is a nice simple solution and would be a shame to see it left behind /deprecated as sklearn versions progress.

Maybe a bit of a simple/silly question, but is there any way to persist sklearn models s.t. they don't need retrained with a newer version of sklearn each time? As in, can you:
 - train a model with sklearn 0.24, persist with joblib
 - when 0.25 rolls around not have to run the training script and re-persist so the model is compatible with sklearn 0.25?

I appreciate it's not really a qu specific to this repo but was curious.

**Comment by menkotoglou** [comment]
Hello @mjam03,

The only developer who has permission merge PRs into master is the original author. Since he seems to have dropped this project, @dimitrismistriotis and I decided to maintain this project.

You can find the source code here: https://gitlab.com/dimitrios/alt-profanity-check.

Additionally, we released an alternative version for pip. You can find it here: https://pypi.org/project/alt-profanity-check/.

To answer your question, I don't know (and don't think there is) a way to use a model without installing the version it is trained on.

**Comment by mjam03** [comment]
@koti  Great news! Thanks v much!

Will drop my local fork of @owenjones branch and instead just standard pip install the 'alt version'.

**Review by VitalyChait — APPROVED** [review]

**Pull request closed without merging**
